receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
  otlp:
    endpoint: tempo:4317 
    tls:
      insecure: true 

service:
  pipelines:
    traces: 
      receivers: [otlp]
      processors: []
      exporters: [logging,otlp]

    metrics:
      receivers: [otlp]
      exporters: [debug] 
    logs:
      receivers: [otlp]
      exporters: [debug]